sudo: false
language:
  - python

cache:
  pip: true

python:
  - 2.7

install:
  - pip install flake8
  - pip install -r requirements.txt

script:
  - flake8 --statistics --show-source
<<<<<<< HEAD
  - python -m unittest discover
=======
>>>>>>> f93f49fde6df6f2f9398d44e52a545a3dc6f2921
